### ISSUE TITLE
firebase-collection: Uncaught TypeError: Cannot read property 'slice' of undefined

### ISSUE THREAD

**Issue by bahuma20** [GoogleWebComponents/firebase-element#19]
Using firebase-collection this way:
```html
<!doctype html>
<html lang="">
  <head>
    <meta charset="utf-8">
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Polymer Starter Kit</title>
    
    <script src="bower_components/webcomponentsjs/webcomponents-lite.js"></script>
  
    <link rel="import" href="bower_components/firebase-element/firebase-collection.html">
  </head>
  <body>
    <template is="dom-bind">
      <firebase-collection
        location="https://example.firebaseio.com/entries"
            data="{{entries}}"></firebase-collection>
          <template is="dom-repeat" items="[[entries]]" as="entry">
            <span>[[entry.name]]</span>
          </template>
    </template>
  </body>
</html>
```

Works fine on first run, but when updating it shows following error in the console:
```
firebase-collection: Uncaught TypeError: Cannot read property 'slice' of undefined
```

**Comment by cdata** [comment]
Thanks for reoorting. I'll take a look.

**Comment by birkir** [comment]
I get that as well. Pinpointed this to polymer library in the splice function.

    splice: function(path, start, deleteCount) {
        var array = this.get(path); <--

the "array" variable returns null because the path has not been set, yet.

So, i looked at what path was tried to retrieve:

    this.splice('data' + this.data.indexOf(oldValue), 1, value);

Resulted in `"data-1"` that's not a valid path. Something like `"data.0"` or `"data.5"` etc. is probably needed. So finding the correct position of item in the array is needed.

See https://github.com/Polymer/polymer/issues/1661

**Comment by cdata** [comment]
This is fixed in https://github.com/GoogleWebComponents/firebase-element/pull/26
